### ISSUE TITLE
[Issue] Open private channel

### ISSUE THREAD

**Issue by wallace4BR** [DiSkyOrg/DiSky#101]
```discord command .test:
	trigger:
		open private channel of event-user and store it in {_channel}
		broadcast "%{_channel}%"
```
![image](https://user-images.githubusercontent.com/81590228/203461929-b3257fc3-09d3-44b0-b78c-1160ceae4b68.png)

The variable is always set, even thought my DM's are closed, making the effect useless

**Comment by SkyCraft78** [comment]
It was a top-level error, as the async effects were not clearing the variable if the inputs was null.
