### ISSUE TITLE
Issues with some DiSky syntaxes executed at same time

### ISSUE THREAD

**Issue by AndroZzz** [DiSkyOrg/DiSky#103]
DiSky version: v4.7.0 (latest)
Skript version: v2.6.4 (latest)
Paper version: 1.16.5-R0.1-SNAPSHOT

Link to debug file: https://pastebin.com/8Sk5sU0k

When executing the same function two times in a row, with differents arguments, but without delay, DiSky syntaxes that require a restaction can cause "trigger" to be cloned, even if it's a function, event, custom effect etc...

Code example:
```
options:
    bot: test
    id1: message_id_1
    id2: message_id_2
    channel: channel_id_of_messages

function test(n: number):
    set {_bot} to bot named "{@bot}" # Storing bot object
    set {_c} to channel with id "{@channel}" with bot {_bot} # Storing channel object
    if {_n} is 1:
        set {_id} to "{@id1}" # Storing message id 1 for first execution
    if {_n} is 2:
        set {_id} to "{@id2}" # Storing message id 2 for second execution
    retrieve message with id "%{_id}%" from {_c} using bot {_bot} and store it in {_m} # Retrieving message
    edit message {_m} to show "Edit ##%{_n}%" # Editing message with {_n} variable

on load:
    test(1)
    test(2)
```

With that code, normally, because the variable {_n} is not modified, first message should be edited with text "Edit #1" and the second message "Edit #2", but it's not the case, output in Discord: 
![image](https://user-images.githubusercontent.com/19236378/206853967-78ec57cd-28cc-429f-8005-fecf66dad3cd.png)

Adding log messages helps to better understand the issue: (using skript-reflect for events hashcode)
```
options:
    bot: test
    id1: message_id_1
    id2: message_id_2
    channel: channel_id_of_messages

function test(n: number):
    broadcast "&aStart %{_n}% - %event.hashCode()%" # NEW: Log message at start of the function
    set {_bot} to bot named "{@bot}" # Storing bot object
    set {_c} to channel with id "{@channel}" with bot {_bot} # Storing channel object
    if {_n} is 1:
        set {_id} to "{@id1}" # Storing message id 1 for first execution
    if {_n} is 2:
        set {_id} to "{@id2}" # Storing message id 2 for second execution
    broadcast "&6Check %{_n}% - %event.hashCode()%" # NEW: Log message before DiSky syntaxes !!!
    retrieve message with id "%{_id}%" from {_c} using bot {_bot} and store it in {_m} # Retrieving message
    edit message {_m} to show "Edit ##%{_n}%" # Editing message with {_n} variable
    broadcast "&cEnd %{_n}% - %event.hashCode()%" # NEW: Log message after DiSky syntaxes
on load:
    test(1)
    test(2)
```
Log messages contains the {_n} variable and the hashcode of the event, to better see the issue of "trigger" clone.

Output in console of the second code:
![image](https://user-images.githubusercontent.com/19236378/206854338-d5c1966c-c0b6-40c0-a089-a24716c9e069.png)

You can see that after DiSky syntaxes, the first function has been voided, and is now the second function, having the same {_n} variable, and the same event by looking at hashcode. The first function is a clone of the second, in the code, `test(1)` only work at the start of the function, but after DiSky syntaxes, `test(1)` is now `test(2)`. Running the code result in having two times `test(2)` in the code, but none of `test(1)`.

If DiSky syntaxes are modified with JDA methods (using skript-reflect), the issue is gone, and functions work properly.

For retrieving messages:
```
    set {_msg} to {_c}.retrieveMessageById("%{_id}%").complete()
```
For editing messages:
```
    set {_edit} to new MessageEditBuilder()
    {_edit}.applyCreateData({_msgbuilder}.build())
    {_msg}.editMessage({_edit}.build()).queue()
````

**Comment by SkyCraft78** [comment]
That's not a bug on DiSky but on Skript: The effect that causes this is the `retrieve member`.
When managing stuff that JDA or DiSky does not cache, we have to send a new request to Discord's API and wait for its answer.
Thanks to DiSky, all the "request" effects (including editing/retrieving/deleting) are async, which means they run on another Thread to not lock the one Minecraft is running (as waiting for the response would take ms).
Skript's function does not support timings & delays, which means any async effect from DiSky (and from other addons tho) won't make the excepted behavior. The only way to fix that currently is to use **skript-reflect's custom syntax**, as they do supports timings.

> Also, `retrieveMessageById` is the method that ask the requests to Discord, and you're locking your thread (aka losing lots of performance) using `complete` on it.
