### ISSUE TITLE
Open private channel

### ISSUE THREAD

**Issue by Notialys** [DiSkyOrg/DiSky#104]
Good evening, with version 4.7 of Disky, I encounter a problem with private messages, when the person has private messages disabled, it returns an error on the console and we cannot even broadcast the variable.

`open private channel of event-user and store it in {_channel}
broadcast {_channel}
if {_channel} is not set:
    reply with "Please enable your private messages!"
else:
    post "Hello world!" to {_channel}`

![chrome_oC6O1xDayA](https://user-images.githubusercontent.com/97785593/208162453-0677be0a-3afa-4261-aeaa-9228180b0eb5.png)

Thank you, if you have a solution for me.

**Comment by Notialys** [comment]
I just tried with version 4.8 and it seems that the variable does not empty, private message closed, it returns the console error.

![chrome_jQvGylHNZt](https://user-images.githubusercontent.com/97785593/208164529-ad852abc-c3fe-4862-8f0e-0df2c9b0f971.png)

**Comment by Mushkrem** [comment]
It's impossible to check if you can send a message to a user before sending it.
You can, however, check if the message was sent with a `last disky exception` expression, eg:
```
open private channel of event-user and store it in {_channel}
post "1" to {_channel}
if last disky exception is set:
    reply with "Message couldn't be sent."
```

**Comment by Notialys** [comment]
I tried and it works, thank you very much.
