### ISSUE TITLE
Reaction emote custom

### ISSUE THREAD

**Issue by Notialys** [DiSkyOrg/DiSky#105]
Good evening, I have a problem with the reactions belonging to a discord server, the emote is displayed well in the reaction but as soon as I type the command or click on the reaction, I have a message that appears and does not launch not the "to run" function so I tried with the basic emotes, for example "smile" and it works.

Version Disky 4.8.0 
Version Skript 2.6.4

![sublime_text_zgjnzanPmV](https://user-images.githubusercontent.com/97785593/208167245-99241062-742d-4dfe-97d8-01671fd9e4a5.png)
![chrome_lg9CzHB1e3](https://user-images.githubusercontent.com/97785593/208167254-bf711578-cd0a-4529-896d-85f850fd3bfc.png)

**Comment by SkyCraft78** [comment]
Hi :wave:
I think the emoji you input was not parsed correctly, cached, or found.
Try to use only the emoji's ID in that case, and specify the guild.

**Comment by Notialys** [comment]
Hey,
I tried too, but nothing works

**Comment by SkyCraft78** [comment]
Although this error is not user-friendly, it means one of the emote is null/not set.
Check if the bot can use the specified emoji, use the correct syntax (aka if you use the emoji's name also specify its guild, same if you use the emoji's id), and try to make it uses the emotes manually (in plain mention, such as `<:disky:000000>`).

**Comment by Notialys** [comment]
I tried with the identifier, the name with and without guild, it does the same thing except if I do not include the guild which returns me information by telling me to specify it.
The emoji works very well on embeds, messages and others whether with the identifier or its name, even on other guilds.
