### ISSUE TITLE
Bring back with files for embeds.

### ISSUE THREAD

**Issue by KajusLion** [DiSkyOrg/DiSky#109]
In earlier versions this worked for me (DiSky and SkImage)
```
		make embed:
			set embed color of embed to lime
			set image of embed to "attachment://image-1.png"
		reply with last embed with files {_img}
```
But now it's broken because someone decided to remove **with files** thingy.
(This is a suggestion)

**Comment by SkyCraft78** [comment]
You will have to use a rich message or an inline message builder. I'll link the inline builder doc in the attachment here, and here is the wiki page for the rich messages: https://docs.disky.me/advanced-stuff/advanced-messages
![image](https://user-images.githubusercontent.com/50667548/210157735-eba05bb6-ac17-4ec2-9cea-fa2481a2a7a8.png)
