### ISSUE TITLE
Internal error in console. 50001

### ISSUE THREAD

**Issue by NopeProsOnly** [DiSkyOrg/DiSky#110]
My code has no errors. And yet something isn't right. I'll send more here when asked.

**Comment by CerialPvP** [comment]
that code means you don't have access to something. it is not a disky bug, its something to do with you. open a thread in support at disky discord

**Comment by NopeProsOnly** [comment]
The disky discord is seperated from the skript discord?

**Comment by CerialPvP** [comment]
the skript discord is for general skripting questions (and help for some **popular** addons), disky is a huge addon so yes there is a separate discord
