### ISSUE TITLE
issue with exceptions

### ISSUE THREAD

**Issue by wallace4BR** [DiSkyOrg/DiSky#114]
code
```
command -send <number>:
	trigger:
		set {_g} to "0"
		retrieve member with id {_m} from {_g} and store it in {_me}
		open private channel of {_me} and store it in {_c}
		post "%arg-1%" to {_c}
		broadcast "%last disky exception%"
```

Issue: if used a unknow member id, the execution stops
![image](https://user-images.githubusercontent.com/81590228/217928756-290fd39d-74b3-4377-beda-deaafcbd3988.png)

**Comment by SkyCraft78** [comment]
Should be fixed here:
https://github.com/DiSkyOrg/DiSky/commit/17f75012aa978b9d125e48e3e191d377b5cc78b1
Tysm for the report!
