### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Hurming** [DiSkyOrg/DiSky#115]
proplem with `event-role` in `on role add`
proplem with `event-invite` in `on member join`
![imagdwdwd](https://user-images.githubusercontent.com/61734952/219757695-94446eff-3f6e-454d-9531-8c3a42454fde.png)

**Comment by SkyCraft78** [comment]
`event-roles` should work for the first one.
The second one just does not exist.

**Comment by Hurming** [comment]
> `event-roles` should work for the first one. The second one just does not exist.

i test `event-roles` its not work too same error

**Comment by Hurming** [comment]
![image](https://user-images.githubusercontent.com/61734952/219759979-fa645c07-90eb-4544-973f-59f189605049.png)

**Comment by SkyCraft78** [comment]
What's your DiSky version? You are in which event?

**Comment by Hurming** [comment]
> What's your DiSky version? You are in which event?

4.9.0

**Comment by SkyCraft78** [comment]
Also, `event-roles` return roles, not strings. You'll have to use contains to check.

**Comment by Hurming** [comment]
> 

![image](https://user-images.githubusercontent.com/61734952/219761863-68ce5247-6cb0-49e8-9ad4-5b6a2a6d6a16.png)

**Comment by SkyCraft78** [comment]
Looks like Skript doesn't like when we override its own expressions.
Use `array event-roles` for now, I'll see for a bypass soon.

**Comment by Hurming** [comment]
> array event-roles

fanily this work `array event-roles`
and thanks if u fix it soon

**Comment by Hurming** [comment]
> Looks like Skript doesn't like when we override its own expressions. Use `array event-roles` for now, I'll see for a bypass soon.

and what about `event-invite`

**Comment by SkyCraft78** [comment]
> The second one just does not exist.

**Comment by Hurming** [comment]
> > The second one just does not exist.

then why u add it in Disky docu
![image](https://user-images.githubusercontent.com/61734952/219783904-f32a31bd-a1e4-42ea-aba0-c28999aa0f24.png)

**Comment by SkyCraft78** [comment]
That's not an event value but an expression. You'll have to learn Skript before using DiSky tho.
