### ISSUE TITLE
Error Console

### ISSUE THREAD

**Issue by xApafaas** [DiSkyOrg/DiSky#125]
![image](https://user-images.githubusercontent.com/93076354/229084358-068f9335-f70e-40b6-92ac-eefec58090ec.png)

**Comment by SkyCraft78** [comment]
Hey there :)
Can you tell us in what situation this happen exactly?
Basically, this error means you have sent an interaction to a user, the bot has been shut down and this user tries to interact with the previously-sent interaction.

**Comment by xApafaas** [comment]
Hey, 
![image](https://user-images.githubusercontent.com/93076354/229200443-d34197b2-a46e-403e-b778-a6bc7b2144e9.png)

**Comment by SkyCraft78** [comment]
Is the error still happening today? Has it even happens again tho?

**Comment by ItsTheSky** [comment]
Bump
