### ISSUE TITLE
Issue With Tickets

### ISSUE THREAD

**Issue by TheWeirdCoder** [DiSkyOrg/DiSky#126]
So i have some code but its this part thats confusing

`remove view channel from permissions of public role of event-guild in {_ticket}`
   `remove message send from permissions of public role of event-guild in {_ticket}`
       ` add (view channel) to permissions of member with id {_id} in {_ticket}`
       ` add (message send) to permissions of member with id {_id} in {_ticket}`

It does not remove the permissions. Any clue why? (Got this code from someone else)

**Comment by TheWeirdCoder** [comment]
PS:

`remove (view channel) from (permissions of public role of event-guild) in {_ticket}`
`add (message send) to permissions of member with id {_id} in {_ticket}`
`remove (message send) from (permissions of public role of event-guild) in {_ticket}`
` add (view channel) to permissions of member with id {_id} in {_ticket}`

This doesnt work either.

**Comment by SkyCraft78** [comment]
Be sure to debug everything. What is your DiSky & Skript version?

**Comment by ItsTheSky** [comment]
Bump
