### ISSUE TITLE
Multiple event-values missing in several events

### ISSUE THREAD

**Issue by sluhtie** [DiSkyOrg/DiSky#134]
I tested the on message receive/delete/edit events and noticed that although the message gets cached correctly following issues occur:

```
on message delete:
- event-string returns none
- event-message returns none

on message edit:
- event-string returns none
```

Code I have used:
```
on message receive:
    broadcast "---> MESSAGE SEND"
    broadcast "%event-user%"
    broadcast "%event-guild%"
    broadcast "%event-newschannel%"
    broadcast "%event-guildchannel%"
    broadcast "%event-member%"
    broadcast "%event-bot%"
    broadcast "%event-textchannel%"
    broadcast "%event-privatechannel%"
    broadcast "%event-message%"
    broadcast "%event-threadchannel%"

on message edit:
    broadcast "---> MESSAGE EDITED"
    broadcast "%event-guild%"
    broadcast "%event-newschannel%"
    broadcast "%event-guildchannel%"
    broadcast "%event-bot%"
    broadcast "%event-textchannel%"
    broadcast "%event-privatechannel%"
    broadcast "%event-message%"
    broadcast "%event-string%"
    broadcast "%event-threadchannel%"
    
on message delete:
    broadcast "---> MESSAGE DELETED"
    broadcast "%event-guild%"
    broadcast "%event-newschannel%"
    broadcast "%event-number%"
    broadcast "%event-guildchannel%"
    broadcast "%event-bot%"
    broadcast "%event-textchannel%"
    broadcast "%event-privatechannel%"
    broadcast "%event-message%"
    broadcast "%event-string%"
    broadcast "%event-threadchannel%"
```

Responses I have received with testing:
![grafik](https://github.com/DiSkyOrg/DiSky/assets/97464371/e338437e-db57-48ee-8ac9-e56bbc65c15d)

**Comment by sluhtie** [comment]
I also noticed that there is no event-member when firing either the message delete/receive or edit event. This would be useful aswell

**Comment by ItsTheSky** [comment]
> look

?

**Comment by ItsTheSky** [comment]
## Hey there 👋

First, Are the messages that return `none` for the different event-value cached in DiSky? *you can see that by enabling the debug mode in the configuration. It'll send a message every time a message is cached with its ID and content*

---

**retrieved** values can be accessed using the `retrieve event value` effect (https://disky.me/wiki/docs/effects/#retrieveeventvalue). The most common available value for any **log-related event** (aka any event that adds an audit log to the guild's logs) is `author`, and it'll be the actual author of the action (the user who banned someone for instance). I hope I was clear!

For any time-related values (such as previous boost count or tier), you'll have to use Skript's temporal system. For instance, you can get the previous boost tier using `past event-string`, or `past event-integer` for the previous boost count.
> I know this is not suitable for comprehension to have such *weird* name for event values, however, that's how Skript works and I cannot do anything against that.

For the last one, that you also quoted in your last message, I don't think I miss any value, as I can only get the guild, previous and new values. Correct me if I'm wrong tho!

---

The event you suggested should be added in the next release, aka v4.12.0! Thanks for it :)

**Comment by sluhtie** [comment]
Hey, yes. I already enabled debugging and the messages get cached indeed.
(See Screenshot of Terminal)

Also, shouldn't there be some way to get the member that boosted the server then?!

**Comment by ItsTheSky** [comment]
Well according to https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/events/guild/update/GuildUpdateBoostCountEvent.html, I don't think it's possible :/

**Comment by sluhtie** [comment]
Mhhh any work around? I mean there must be some way to have a var with the amount a user boosted the server

**Comment by ItsTheSky** [comment]
Not to my knowledge, although you can "cheat" by getting the system message sent when someone boosts maybe?

**Comment by sluhtie** [comment]
I know theres a bot that counts the boosts of a user.
https://boosterbot.xyz/ I wonder how they did it
