### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by TBAProgramming** [DiSkyOrg/DiSky#135]
list of plugins i using:

![image](https://github.com/DiSkyOrg/DiSky/assets/121028379/125eaa11-33ab-4b42-af1b-25757981d609)

its not working and coloured with red in /plugins

my skript:

```
define new bot named "Bot":
	
	token: XXX
	
	intents: default intents
	
	policy: all
	auto reconnect: true
	compression: none
```

i forget to add disky version: 4.11.1

**Comment by TBAProgramming** [comment]
Can someone help me?

**Comment by ItsTheSky** [comment]
Can we have some more information, such as Skript and server version please?

**Comment by TBAProgramming** [comment]
OH i sry for posting my token I forget to no post it my server version: paper paper-522 {1.19.4}
skript: 
![image](https://github.com/DiSkyOrg/DiSky/assets/121028379/4d21883f-64d9-49ee-b584-eb5873ba9464)

**Comment by TBAProgramming** [comment]
![image](https://github.com/DiSkyOrg/DiSky/assets/121028379/2e507a1f-048e-4852-8683-c1e864aa2b26)

`define new bot named "Bot":
 
    token: Hidden
 
    intents: default intents
 
    policy: all
    auto reconnect: true
    compression: none
 
 
discord command ping:
    prefixes: !
    trigger:
        reply with "Pong!"
 
 
discord command hi [<text>]:
    prefixes: !
    trigger:
        if arg-1 is not set:
            reply with "Enter a player to say hi to!"
        else:
            reply with "Hi %arg-1%!"
 
discord command playing [<text>]:
    prefixes: !
    trigger:
        if arg-1 is not set:
            reply with "Enter a game to play!"
        else:
            set the presence of the bot named "Bot" to playing arg-1`

**Comment by TBAProgramming** [comment]
i using disky and problem solved

**Comment by TBAProgramming** [comment]
but disky 4.11.1 is not working
