### ISSUE TITLE
Attachments not working such as embed images and thumbnails

### ISSUE THREAD

**Issue by sluhtie** [DiSkyOrg/DiSky#136]
# Attachments 
Since the beta version I am no longer able to add image attachments to a message using 

`
add ... to attachments of message
`

# Embed Images
Also I noticed before already that for some reason I'm not able to add thumbnails not images to an embed anymore. They don't give me any error unlikely as the attachemt issue, they just don't show on the embed anymore.

`
set thumbnail of embed to "image url"
`
`
set image of embed to "image url"
`

**Comment by ItsTheSky** [comment]
Is that still up to date for all reports? We talked about this on Discord but lost the lead 😅

**Comment by sluhtie** [comment]
> Is that still up to date for all reports? We talked about this on Discord but lost the lead 😅

So the attachements yes, the images and thumbnails of embed no.
![grafik](https://github.com/DiSkyOrg/DiSky/assets/97464371/05fa1e26-f990-4e77-8469-e383f3a6b7bd)

**Comment by ItsTheSky** [comment]
I thought about that, but maybe Skript does not accept mixing types in arrays? Are those all images (the functions)?

**Comment by sluhtie** [comment]
You have send a custom edited version of disky beta2 in the discord. This error doesen't appear on that version but on the public release it does

**Comment by sluhtie** [comment]
> 

Yes they all return a image type

**Comment by ItsTheSky** [comment]
With the latest beta4 it also appears?!

**Comment by sluhtie** [comment]
There is no beta4.

**Comment by ItsTheSky** [comment]
The latest release it 4.12.0-beta4: https://disky.me/resources/index.php?resources/disky-official-resource.5/

**Comment by sluhtie** [comment]
Download it and check, it's actually 4.12.0-beta3

**Comment by ItsTheSky** [comment]
*yeah I may have forgotten to change the internal version name :x*, but does it also happens there?

**Comment by sluhtie** [comment]
yes it does

**Comment by ItsTheSky** [comment]
Got it, imma investigate that in the afternoon 👌
