### ISSUE TITLE
Missing `&` in bot invite URL in wiki

### ISSUE THREAD

**Issue by Noumaa** [DiSkyOrg/DiSky#139]
Hey!
In [this page](https://disky.me/wiki/getting-started/bot-creation/) on the wiki, this link :
`https://discord.com/api/oauth2/authorize?client_id=XXXXXXXXXXXXXXXXXX&permissions=8scope=bot%20applications.commands`
Doesn't work and miss that `&` before defining the scope variable :
`https://discord.com/api/oauth2/authorize?client_id=XXXXXXXXXXXXXXXXXX&permissions=8&scope=bot%20applications.commands`

**Comment by ItsTheSky** [comment]
Fixed
