### ISSUE TITLE
when i load in my server it shows a bunch of errors with disky i need helpp

### ISSUE THREAD

**Issue by Kermitmyfrog** [DiSkyOrg/DiSky#152]
there a bunch of errors when i load in disky

**Comment by CerialPvP** [comment]
And, where is the error?? We can't do anything if you don't provide the errors.

**Comment by EquipableMC** [comment]
I fixed it for him, he was an error with his code because his developer didn't set something right.

**Comment by ItsTheSky** [comment]
> I fixed it for him, he was an error with his code because his developer didn't set something right.

Perfect thanks! Closing that
