### ISSUE TITLE
DiSky completely breaks all packet listeners?

### ISSUE THREAD

**Issue by DontSharee** [DiSkyOrg/DiSky#153]
When using a packet listener like simple-packets or skript-packet with disky, none of the events get fired for some reason. Very bad bug

**Comment by ItsTheSky** [comment]
Does it still happen without DiSky? And please provide versions, maybe code that is using packet addons? 
To my knowledge DiSky does not interfer anyhow with Minecraft itself so there's no way it could technically break packets.

**Comment by ItsTheSky** [comment]
Can I have some code and versions, please?
