### ISSUE TITLE
I got this error when trying to make livec status bot

### ISSUE THREAD

**Issue by SRSFFGAMING** [DiSkyOrg/DiSky#156]
![Screenshot_2023-11-28-06-42-57-74_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/DiSkyOrg/DiSky/assets/99670587/17da807c-6da4-42d4-8b69-971df1d577ee)
![Screenshot_2023-11-28-06-43-15-06_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/DiSkyOrg/DiSky/assets/99670587/0f084fce-74a5-450c-abcd-acd6db348abf)

**Comment by ItsTheSky** [comment]
Hey there! As said in the error (in yellow), **read the error carefully**! It says you're trying to get a non-loaded bot, called `SRS-TAMIZHAN-NETWORK`.
