### ISSUE TITLE
retrieve member no longer works.

### ISSUE THREAD

**Issue by EquipableMC** [DiSkyOrg/DiSky#164]
After some testing, this:
```
discord command ?unban <string>:
	trigger:
		if event-member has discord role with id "1195839650514882670":
			set {_unbanneduser} to arg-1
			retrieve member with id {_unbanneduser} from guild with id "1188896649540538388" and store it in {_user}
			discord unban {_user} from guild with id "1188896649540538388"
			reply with "cool"
``` 

returns an error message for unknown member (banning), but if I remove `from guild with id "1188896649540538388"`, it throws an `Variables cannot be used here` error with no way of fixing.

**Comment by Mushkrem** [comment]
I'm confused. Why wouldn't that be the expected result?
As a side note, here's an image i just generated:
![image](https://github.com/DiSkyOrg/DiSky/assets/50112831/031e3f58-36f0-4ea6-87ae-a4de3157372d)
It brought me immense joy, thought I'd share.

**Comment by EquipableMC** [comment]
I figured out the issue. My editor wasn't saving properly + with the way skript handles some stuff

**Comment by EquipableMC** [comment]
> I'm confused. Why wouldn't that be the expected result?
> 
> As a side note, here's an image i just generated:
> 
> ![image](https://github.com/DiSkyOrg/DiSky/assets/50112831/031e3f58-36f0-4ea6-87ae-a4de3157372d)
> 
> It brought me immense joy, thought I'd share.
> 
> 

Disky isues my favorite text
