### ISSUE TITLE
Error after reloading bot Skript.

### ISSUE THREAD

**Issue by skTanky** [DiSkyOrg/DiSky#167]
![image](https://github.com/DiSkyOrg/DiSky/assets/121093474/661065d9-3fe2-45b2-b2de-5d199be64296)

**Comment by EquipableMC** [comment]
Skript Version?

**Comment by skTanky** [comment]
2.7.3 sir

**Comment by Mushkrem** [comment]
It appears to me that the issue at hand could be attributed to a disruption in your server’s connectivity. Perhaps you are attempting to execute an operation on Discord subsequent to the disconnection of your bot? The problem could also originate from your host. Intriguingly, I could hypothesize endlessly about the nature of your difficulties, given the absence of additional information pertaining to your server or the code in use, how exciting!
