### ISSUE TITLE
NoSuchMethod Error

### ISSUE THREAD

**Issue by akaBayest** [DiSkyOrg/DiSky#182]
Server Version: 1.20.4
Skript Version: 2.8.3
Disky Version: v4.14.2

Whenever I reload the bot script I keep getting this weird error and I can't really find a solution to it,
Here's the full error message:
https://pastebin.com/qpUtnb8D

**Comment by EquipableMC** [comment]
What is your webhook version?

**Comment by ItsTheSky** [comment]
Update to the new webhooks version (1.0.2) :)
