### ISSUE TITLE
idk what is this :)

### ISSUE THREAD

**Issue by Hurming** [DiSkyOrg/DiSky#185]
30.04 09:28:35 [Server] Craft Scheduler Thread - 34/INFO DiSky Internal Error (version: 4.15.1)
30.04 09:28:35 [Server] Craft Scheduler Thread - 34/INFO Error type: IllegalStateException
30.04 09:28:35 [Server] Craft Scheduler Thread - 34/INFO This interaction has already been acknowledged or replied to. You can only reply or acknowledge an interaction once!
30.04 09:28:35 [Server] Craft Scheduler Thread - 34/INFO Full Stacktrace:
30.04 09:28:35 [Server] Craft Scheduler Thread - 34/INFO net.dv8tion.jda.internal.requests.restaction.interactions.InteractionCallbackImpl.tryAck(InteractionCallbackImpl.java:57)
30.04 09:28:35 [Server] Craft Scheduler Thread - 34/INFO net.dv8tion.jda.internal.requests.restaction.interactions.InteractionCallbackImpl.submit(InteractionCallbackImpl.java:81)
30.04 09:28:35 [Server] Craft Scheduler Thread - 34/INFO net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:225)
30.04 09:28:35 [Server] Craft Scheduler Thread - 34/INFO net.dv8tion.jda.api.requests.RestAction.complete(RestAction.java:632)
30.04 09:28:35 [Server] Craft Scheduler Thread - 34/INFO info.itsthesky.disky.elements.effects.DeferInteraction.execute(DeferInteraction.java:76)
30.04 09:28:35 [Server] Craft Scheduler Thread - 34/INFO ch.njol.skript.util.AsyncEffect.lambda$walk$1(AsyncEffect.java:60)
30.04 09:28:35 [Server] Craft Scheduler Thread - 34/INFO org.bukkit.craftbukkit.v1_20_R4.scheduler.CraftTask.run(CraftTask.java:82)
30.04 09:28:35 [Server] Craft Scheduler Thread - 34/INFO org.bukkit.craftbukkit.v1_20_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
30.04 09:28:35 [Server] Craft Scheduler Thread - 34/INFO java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
30.04 09:28:35 [Server] Craft Scheduler Thread - 34/INFO java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
30.04 09:28:35 [Server] Craft Scheduler Thread - 34/INFO java.base/java.lang.Thread.run(Thread.java:1583)
30.04 09:28:35 [Server] Craft Scheduler Thread - 34/INFO READ THE ERROR CAREFULLY, and if you are sure about it,
30.04 09:28:35 [Server] Craft Scheduler Thread - 34/INFO you can report the error with the whole stacktrace on the GitHub repository:
30.04 09:28:35 [Server] Craft Scheduler Thread - 34/INFO https://github.com/DiSkyOrg/DiSky/issues/new

**Comment by EquipableMC** [comment]
This interaction has already been acknowledged or replied to. You can only reply or acknowledge an interaction once!
