### ISSUE TITLE
Changing the order of channels/channel position

### ISSUE THREAD

**Issue by theOneSchrill** [DiSkyOrg/DiSky#187]
## A syntax to make channels change their position would be cool

**A syntax to change channels order**
I want to change one channels position, the other channels shall move accordingly, pretty much just the same process as when u do it manually in your discord servers settings.

**'set channel position of event-channel to (channel position of event-channel)+1'**
no

- [x] I already **searched** for this feature on [**DiSky's Documentation/Wiki**](https://disky.me/docs/home/) and I'm sure it's not there
(I was told to suggest it <3)

**Comment by ItsTheSky** [comment]
Are you talking about [this expression](https://disky.me/docs/docs/expressions/#channelposition)? You can modify it, have you tried it yet?

**Comment by theOneSchrill** [comment]
Yea I've tried it with that expression but when I used `set channel position of event-channel to (channel position of event-channel)+1` it didnt change the position of the channel (same with -1)

**Comment by ItsTheSky** [comment]
Hi there! After some tests, It seems a lot of weird things are happening with the syntax. Can you try using the possession pattern? For instance:
```applescript
set <channel>'s channel position to {_pos}
```

**Comment by theOneSchrill** [comment]
Hey! So after trying this, it seems like some channels are moving only and they're moving a little weird. The channel which I selected was at position 1 (of a total of 3 channels). The channel got moved to position 3 instead of 2. After that, I couldn't move it back up with my up button
Code:
`            set {_c} to channel with id (3rd element of (split event-string at ".")) using event-bot
            event-string = "channel.position.%discord id of {_c}%.1dir":
                set {_pos} to (channel position of {_c})+1
                set {_c}'s channel position to {_pos}
                reply with hidden "up"
            event-string = "channel.position.%discord id of {_c}%.2dir":
                set {_pos} to (channel position of {_c})-1
                set {_c}'s channel position to {_pos}
                reply with hidden "down"`
the bot successfully replies with up and down, depending what button I click on.

**Comment by ItsTheSky** [comment]
Yup, the whole logic I did behind was broken (cuz math wasn't mathing). Although it got fixed, it seems positioning two channels at the same position will make them re-arrange in another way (sorted by creation date).
I'll close this issue as I got it working fine on my end with v4.16.0 that's coming soon. Feel free to open a new one if the problem persists!
