### ISSUE TITLE
add new custom Presence

### ISSUE THREAD

**Issue by Hurming** [DiSkyOrg/DiSky#189]
like remove the idle or online or offline ...
just custom ![image_2024-05-03_184608041](https://github.com/DiSkyOrg/DiSky/assets/61734952/a0ca9fc3-5a35-4248-bd15-2d619e843dc7) & Status

**Comment by ItsTheSky** [comment]
#190 (it's in DiSky already but not yet documented)

**Comment by Hurming** [comment]
> #190 (it's in DiSky already but not yet documented)

How can i use it or post it in website
