### ISSUE TITLE
On kick event.

### ISSUE THREAD

**Issue by Manshoun** [DiSkyOrg/DiSky#191]
I believe there is an on kick event but that is not so advanced. A value for The person who was kicked is missing. A value, the one who kicked it. And a value for the kick reason.

**Comment by ItsTheSky** [comment]
Whoa, it was much more complicated as we normally have 0 information about the kick event (not even the user who has been kicked, or the one who kicked), so I used a small trick to combine two events. At the end, this event has been added, thanks for the suggestion!
