### ISSUE TITLE
reset permissions

### ISSUE THREAD

**Issue by Hurming** [DiSkyOrg/DiSky#197]
This thing already exists, but I want you to change Expressions from remove all to reset, for example
change it from `remove all (your permissions) from permissions of event-member in event-channel`
to `reset (your permissions) from permissions of event-member in event-channel`
and add the Expressions in https://disky.me/docs/docs/expressions/?h=permission

and add new thing doing remove member or role from permission list in channel
like `clear member/role from permissions of event-channel`
![image_2024-05-09_160001454](https://github.com/DiSkyOrg/DiSky/assets/61734952/e546bb3b-9f56-44d3-9b0a-3d1ba8cb60d3)

**Comment by ItsTheSky** [comment]
The `reset` mode does not exist in Skript, as the expression is directly used by Skript's changer. It would require creating a whole new change effect with just one new pattern.

**Comment by Fusezion** [comment]
> The `reset` mode does not exist in Skript, as the expression is directly used by Skript's changer. It would require creating a whole new change effect with just one new pattern.

Sorry a little confused here, RESET does indeed exist
https://github.com/SkriptLang/Skript/blob/b0052d25d6314c0cf7279d089aa4201bad23f713/src/main/java/ch/njol/skript/classes/Changer.java#L39-L41
