### ISSUE TITLE
Retrieve Owner

### ISSUE THREAD

**Issue by xApafaas** [DiSkyOrg/DiSky#198]
## Versions

- DiSky: `v4.16.0`
- Skript: `v2.8.4`
- Paper: `v1.16.5`

## Description

La syntaxe "retrieve owner.. " marchait en 4.12.1 mais plus actuellement.

Variables cannot be used here.
Line: retrieve owner in {_g} and store it in {_owner}

Unknown event value 'guild and store it'
Line: retrieve owner in event-guild and store it in {_owner}

## Acknowledgment

- [x] I have **read** the error correctly, and I'm **sure** it's directly a DiSky problem.
- [x] I have **searched** for **similar** bugs on the [**Issues tab**](https://github.com/DiSkyOrg/DiSky/issues)

**Comment by Hurming** [comment]
Try to user
`retrieve owner from guild with id discord id of event-guild and store it in {_ownership}
`

**Comment by ItsTheSky** [comment]
replace `in` by `of` or `from`
