### ISSUE TITLE
Get Status of member

### ISSUE THREAD

**Issue by xApafaas** [DiSkyOrg/DiSky#199]
## Description

Pouvoir detecter le statut d'un membre afin de pouvoir attribuer un rôle (Soutien), il y a le statut avec le lien Discord

## Aknowledgement

- [x] I already **searched** for this feature on [**DiSky's Documentation/Wiki**](https://disky.me/docs/home/) and I'm sure it's not there

**Comment by Hurming** [comment]
Yes its not there that's right but u can try
`discord online status of event-member`
https://disky.me/docs/docs/events/?h=status
