### ISSUE TITLE
Retrieve AuditLogs

### ISSUE THREAD

**Issue by xApafaas** [DiSkyOrg/DiSky#200]
## Versions

- DiSky: `v4.16.0`
- Skript: `v2.8.4`
- Paper: `v1.16.5`

## Description

La syntaxe est inconnue pour Disky

Can't understand this condition/effect: retrieve audit logs from event-guild and store it in {_logs::*}
Line: retrieve audit logs from event-guild and store it in {_logs::*}

## Acknowledgment

- [x] I have **read** the error correctly, and I'm **sure** it's directly a DiSky problem.
- [x] I have **searched** for **similar** bugs on the [**Issues tab**](https://github.com/DiSkyOrg/DiSky/issues)

**Comment by Hurming** [comment]
Try to use
`retrieve audit logs from event-guild and store it in {_logs::*}`

**Comment by ItsTheSky** [comment]
The pattern is `retrieve [(all|every)] [audit] log[s] [entries] (from|with|of|in) %guild% [(with|using) [the] [bot] %-bot%] and store (them|the [audit] log[s] [entries]) in %~objects%`. The wiki needs to be updated, but you should've check the docs too :)
