### ISSUE TITLE
Get member who add bot discord

### ISSUE THREAD

**Issue by xApafaas** [DiSkyOrg/DiSky#201]
## Description

Possibilité de detecter le membre qui a ajouté le bot ?

## Aknowledgement

- [x] I already **searched** for this feature on [**DiSky's Documentation/Wiki**](https://disky.me/docs/home/) and I'm sure it's not there

**Comment by ItsTheSky** [comment]
No, discord does not send us this sort of thing. Maybe via OAuth it's possible, but not sure.
