### ISSUE TITLE
Logged author (on guild log create)

### ISSUE THREAD

**Issue by xApafaas** [DiSkyOrg/DiSky#202]
## Versions

- DiSky: `v4.16.0`
- Skript: `v2.8.4`
- Paper: `v1.16.5`

## Description

logged author renvoit "none" à tous les logs !

## Acknowledgment

- [x] I have **read** the error correctly, and I'm **sure** it's directly a DiSky problem.
- [x] I have **searched** for **similar** bugs on the [**Issues tab**](https://github.com/DiSkyOrg/DiSky/issues)

**Comment by ItsTheSky** [comment]
The docs will be updated accordingly, but Discord does not send us the author User itself, only its ID, when **receiving** an audit log (it works fine when retrieving logs tho)

**Comment by xApafaas** [comment]
Can i retrieve a member with its ID ?
