### ISSUE TITLE
add something like "is in guild with id "1170079960183083019""

### ISSUE THREAD

**Issue by Manshoun** [DiSkyOrg/DiSky#203]
i already tried it. No erros but it returns a <none>. I could retrieve then but i want to check like 700 members. That is a hard one then. Maybe you can watch over or add a function for it.

**Comment by EquipableMC** [comment]
You can use `find members in event-guild and store them in {_members::*} with filter var {_m}:`

**Comment by ItsTheSky** [comment]
Yea, you can use the find members section.
