### ISSUE TITLE
"message receive" event is fired twice

### ISSUE THREAD

**Issue by softy-oniguru** [DiSkyOrg/DiSky#215]
## Versions

- DiSky: `v4.17.2`
- Skript: `v2.8.6`
- Paper (Purpur*): `v1.20.4`

## Description

```
on message received:
    broadcast event-bot
    event-user is not bot
    broadcast "&7%event-user's discord id%: %event-message%"
```

its returns message 2 times:
```
[22:51:56 INFO]: (my bot)
[22:51:56 INFO]: 757970149553995788: test
[22:51:56 INFO]: (my bot)
[22:51:56 INFO]: 757970149553995788: test
```

## Acknowledgment

- [ ✔ ] I have **read** the error correctly, and I'm **sure** it's directly a DiSky problem.
- [ ✔ ] I have **searched** for **similar** bugs on the [**Issues tab**](https://github.com/DiSkyOrg/DiSky/issues)

**Comment by softy-oniguru** [comment]
I have already tried to ask for help in the discord, but I have already checked everything myself.

**Comment by softy-oniguru** [comment]
the current way to remove this bug is:
1. Add the discord id of the message to the list
2. Check => remove discord id from the list, stop
```
on message receive:
  if {.::*} contains event-message's discord id:
    remove event-message's discord id from {.::*}
    stop
  add event-message's discord id to {.::*}
```

**Comment by EquipableMC** [comment]
He is wrong. Use the following the code below:

```
on message receive:
    discord id of event-channel is "id"
    event-member is not a discord bot
    broadcast "%event-member %event-message%"
```
