### ISSUE TITLE
banner & avatar & nickname

### ISSUE THREAD

**Issue by Manshoun** [DiSkyOrg/DiSky#216]
there is a way to change the avatar of the bot: set avatar of event-bot to ""

but why is there not a option to change the banner? "set banner of event-bot to """ doesnt work

anddd change the application name is not provided. Only the guild nickname is changeable.

**Comment by EquipableMC** [comment]
> but why is there not a option to change the banner? "set banner of event-bot to """ doesnt work
Sky did not add a way to change it
> anddd change the application name is not provided. Only the guild nickname is changeable.
Changing the application name would cause issues.
