### ISSUE TITLE
on channel delete event

### ISSUE THREAD

**Issue by EquipableMC** [DiSkyOrg/DiSky#217]
## Description

**Describe the solution you'd like**
There should be an event that fires when a channel gets deleted, don't know why this doesn't exist

**Describe alternatives you've considered**
using the audit log stuff

## Aknowledgement

- [✅] I already **searched** for this feature on [**DiSky's Documentation/Wiki**](https://disky.me/docs/home/) and I'm sure it's not there

**Comment by Mushkrem** [comment]
Great idea! There you go: [ChannelDeleteEvent.java](https://github.com/DiSkyOrg/DiSky/blob/master/src/main/java/info/itsthesky/disky/elements/events/channel/ChannelDeleteEvent.java)

**Comment by EquipableMC** [comment]
Then there's 0 documentation on it

**Comment by ItsTheSky** [comment]
> Then there's 0 documentation on it

Feel free to add it :)
https://github.com/DiSkyOrg/Documentation
