### ISSUE TITLE
Role Events

### ISSUE THREAD

**Issue by mempdev** [DiSkyOrg/DiSky#222]
on role add: Does not have an event-role
on role remove: Does not have an event-role
on role change: Should be added so you don't need to have on role add and remove

**Comment by ItsTheSky** [comment]
For both role add and remove events you have `event-roles`, as multiple roles can be added/removed simultaneously by a member.
`on role change` would be useless in my opinion, not only would it offer nothing more than role add/remove, but it would force current devs to refactor their code for no reason.
