### ISSUE TITLE
Disky messes with "is text"

### ISSUE THREAD

**Issue by MissingReports** [DiSkyOrg/DiSky#223]
## Versions

- DiSky: `v4.19.0`
- Skript: `v2.9.0`
- Paper: `v1.20.4`

## Description

For some reason, with Disky everytime I do `if "Whatever" is text` it's always false. It works without disky though
You can try it yourself by testing that condition with and without Disky

**Comment by ItsTheSky** [comment]
I think it should be fixed in 4.20.0. Re-open a new issue if it's still occurring on that version tho, thanks for the report :)
