### ISSUE TITLE
Add custom activity status without activity name such as "playing"/"listening"

### ISSUE THREAD

**Issue by TheJoshue** [DiSkyOrg/DiSky#224]
## Description

**Describe the solution you'd like**
This feature has been added long time ago, it's called Custom Status, it basically shows status without need of activity type such as "playing" or similar

**Describe alternatives you've considered**
/

## Aknowledgement

- [x] I already **searched** for this feature on [**DiSky's Documentation/Wiki**](https://disky.me/docs/home/) and I'm sure it's not there

**Comment by ItsTheSky** [comment]
Hi there, custom status are not available in the presence of discord bots.
