### ISSUE TITLE
User is unable to use dropdown menu after a server restart

### ISSUE THREAD

**Issue by Juliaxe** [DiSkyOrg/DiSky#27]
How to reproduce:

- Make a dropdown menu, contents really don't matter.
- Confirm that it works
- Restart your server
- Try to use your dropdown again, it will not work

**Comment by SkyCraft78** [comment]
The event itself is not fired? 
Can you precise a little bit more what you mean by "it will not work";
Is the user not able to use it (literally, so click on it)? To make choices? Does the bot don't respond?

**Comment by Juliaxe** [comment]
> The event itself is not fired? Can you precise a little bit more what you mean by "it will not work"; Is the user not able to use it (literally, so click on it)? To make choices? Does the bot don't respond?

The bot will no longer respond to the dropdown menu no matter what after a restart unless you reload the skript that hosts the dropdown menu.

**Comment by SkyCraft78** [comment]
This never personally happened to me, it's what I'm using for the LySkee's bot. Does this problem also appear with others events? Or is the dropdown update the only one?

**Comment by Juliaxe** [comment]
> This never personally happened to me, it's what I'm using for the LySkee's bot. Does this problem also appear with others events? Or is the dropdown update the only one?

I haven't tested other events, so I can only say it's for the dropdown menu. The menu will still be there and you can still click things, but the interaction will fail.

**Comment by SkyCraft78** [comment]
Is the whole event that don't fire or is it only a specify trigger section? Can you try to debug it, in addition of others events?

**Comment by Juliaxe** [comment]
> Is the whole event that don't fire or is it only a specify trigger section? Can you try to debug it, in addition of others events?

It's the entire on dropdown click event. No matter what you click, it will always fail **unless** you reload the skript that hosts the dropdown.

**Comment by SkyCraft78** [comment]
I am unable to reproduce this error with the following setup:

- Paper 1.16.5
- Skript 2.6.1
- DiSky v4.0-beta2

Can you send again your server specifications, please?

**Comment by SkyCraft78** [comment]
With the help of @TrasonCo, this issue has been fixed.
It was a problem with the registering step of DiSkyEvents.
