### ISSUE TITLE
Remove Slash commands effect

### ISSUE THREAD

**Issue by CerialPvP** [DiSkyOrg/DiSky#33]
So basically there is no easy way of deleting (or unregistereing) Slash commands. So here are 2 syntaxes.
It will matter if the command is registered either locally or globally. 

Guild syntax:
`remove %slashcommand% from guild %guild%`

Global (Bot) syntax:
`remove %slashcommand% from bot %-bot%`

It will make our lives 10,000 times easier because we have to go through pain to delete commands.
(sky if you see this ur addon is great 10/10)

**Comment by wallace4BR** [comment]
i'm better with `unregister` instead of `remove`

**Comment by SkyCraft78** [comment]
added
