### ISSUE TITLE
[LavaPlayer]: Repeat mode doesn't work

### ISSUE THREAD

**Issue by MinecraftNight4** [DiSkyOrg/DiSky#34]
If you are listening to a song, and you activate the repeat mode, when the music ends it will not continue with the queue and will not repeat the current song, in addition to causing the following error in the console:

> [10:29:16] [JDA AudioConnection Guild: 925226203701452811 Sending Thread/ERROR]: Handler of event com.sedmelluq.discord.lavaplayer.player.event.TrackEndEvent@bc744a39 threw an exception.
> java.lang.IllegalStateException: Cannot play the same instance of a track twice, use track.makeClone().
> 	at com.sedmelluq.discord.lavaplayer.track.BaseAudioTrack.assignExecutor(BaseAudioTrack.java:44) ~[LavaPlayer.jar:?]
> 	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.executeTrack(DefaultAudioPlayerManager.java:346) ~[LavaPlayer.jar:?]
> 	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayer.startTrack(DefaultAudioPlayer.java:115) ~[LavaPlayer.jar:?]
> 	at info.itsthesky.lavaplayer.AudioPlayerWrapper.startTrack(AudioPlayerWrapper.java:108) ~[LavaPlayer.jar:?]
> 	at info.itsthesky.lavaplayer.AudioPlayerWrapper.playTracks(AudioPlayerWrapper.java:49) ~[LavaPlayer.jar:?]
> 	at info.itsthesky.lavaplayer.AudioPlayerWrapper$Handler.onTrackEnd(AudioPlayerWrapper.java:89) ~[LavaPlayer.jar:?]
> 	at com.sedmelluq.discord.lavaplayer.player.event.AudioEventAdapter.onEvent(AudioEventAdapter.java:74) ~[LavaPlayer.jar:?]
> 	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayer.dispatchEvent(DefaultAudioPlayer.java:360) [LavaPlayer.jar:?]
> 	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayer.handleTerminator(DefaultAudioPlayer.java:258) [LavaPlayer.jar:?]
> 	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayer.provide(DefaultAudioPlayer.java:237) [LavaPlayer.jar:?]
> 	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayer.provide(DefaultAudioPlayer.java:212) [LavaPlayer.jar:?]
> 	at info.itsthesky.lavaplayer.AudioPlayerWrapper.provide(AudioPlayerWrapper.java:178) [LavaPlayer.jar:?]
> 	at info.itsthesky.lavaplayer.AudioPlayerSendHandler.canProvide(AudioPlayerSendHandler.java:28) [LavaPlayer.jar:?]
> 	at net.dv8tion.jda.internal.audio.AudioConnection$PacketProvider.getNextPacketRaw(AudioConnection.java:672) [DiSky.4.0-beta2.jar:?]
> 	at net.dv8tion.jda.internal.audio.AudioConnection$PacketProvider.getNextPacket(AudioConnection.java:662) [DiSky.4.0-beta2.jar:?]
> 	at net.dv8tion.jda.api.audio.factory.DefaultSendSystem.lambda$start$0(DefaultSendSystem.java:69) [DiSky.4.0-beta2.jar:?]
> 	at net.dv8tion.jda.api.audio.factory.DefaultSendSystem$$Lambda$4339/0x00000000280d70b0.run(Unknown Source) [DiSky.4.0-beta2.jar:?]
> 	at java.lang.Thread.run(Thread.java:853) [?:?]

**Comment by SkyCraft78** [comment]
Fixed
