### ISSUE TITLE
[LavaPlayer]: "Search in youtube" doesn't work with playlists.

### ISSUE THREAD

**Issue by MinecraftNight4** [DiSkyOrg/DiSky#35]
- When trying to use the "/play" with a playlist that I have, it causes the following result:
https://youtube.com/playlist?list=PLE598t9K58_LLo7eShAUM49uSkVIC5jtb
![image](https://user-images.githubusercontent.com/42017416/167263811-37647f3d-c0f4-4ca1-82e3-dd9228a57d68.png)

- I have tried to use a larger playlist, and the bot did give a result, but it is incorrect as requested. The playlist that I tried to use this time has 390 videos, but the bot could only add 13 videos to the queue(Some songs that the bot added do not belong in the playlist):
https://youtube.com/playlist?list=PL_h4IoimLDtR1XayXb2y6s0OMsoggBt6d
![image](https://user-images.githubusercontent.com/42017416/167263915-ac328263-c4d2-4f5a-b818-cadaccd4625f.png)

**Comment by SkyCraft78** [comment]
This will be related to #62 now, closing this.
