### ISSUE TITLE
Space in name of command

### ISSUE THREAD

**Issue by Ewanbe** [DiSkyOrg/DiSky#37]
Hi ! This is my first issue and I'm not sure how github works. Sorry if I got it wrong. I suggest adding the possibility to put spaces in the name of slash commands.

For exemple :
/quest start <id>
/quest create <name>
/quest delete <id>
/quest set <member> <id>
(this is to show you that the arguments are different and therefore that I can't just do a /quest <string> with a suggest ;)

**Comment by wallace4BR** [comment]
> Hi ! This is my first issue and I'm not sure how github works. Sorry if I got it wrong. I suggest adding the possibility to put spaces in the name of slash commands.
> 
> For exemple : /quest start /quest create /quest delete /quest set (this is to show you that the arguments are different and therefore that I can't just do a /quest with a suggest ;)

That's called subcommands and they are already implemented in disky

**Comment by Ewanbe** [comment]
Ok thank you excuse me ^^
