### ISSUE TITLE
Add evaluate skript code effect

### ISSUE THREAD

**Issue by CerialPvP** [DiSkyOrg/DiSky#38]
So V3 has this effect where you can evaluate Skript code.
So I would like this back for the next DiSky update because it's useful to check if certain lines of code work.

So yeah just the old syntax:
`eval[uate] [without executing] %string% [and store (it|the error[s]) in %-objects%]`

**Comment by aspectxlol** [comment]
Very cool feature plzz add

**Comment by SkyCraft78** [comment]
This could be added to SkUtils, or another addon, but doesn't have its place anymore in DiSky.

**Comment by CerialPvP** [comment]
> This could be added to SkUtils, or another addon, but doesn't have its place anymore in DiSky.

Yeah but thing is SkUtils just doesn't work it sends me errors we can discuss this in DMS or somewhere
