### ISSUE TITLE
Bring back the append effect

### ISSUE THREAD

**Issue by ThatSirWaffles** [DiSkyOrg/DiSky#40]
Hello, so there was `append %string/embedbuilder% to [message] [builder] %messagebuilder%` in v3 before, but it doesn't seem to be in v4. Would be great to have that back too, thanks!

**Comment by SkyCraft78** [comment]
I removed it because it was simply useless.
All you have to do is make a list and join the list with a separator (like `nl`).

**Comment by ThatSirWaffles** [comment]
I see how appending a string to a string would be useless, but the reason that this was useful was to append a string to an embed, and so far that was the only way I knew of doing that, so unless there's another way, it would be great to have it back.
