### ISSUE TITLE
[Bug] Bot won't log on when a token is provided using a string or a variable

### ISSUE THREAD

**Issue by CerialPvP** [DiSkyOrg/DiSky#44]
So when I try to provide a token to login to the bot using a variable, it sends an error that `define new bot named {@bot}` doesn't exist, and when I try to provide the token without a string or a variable, it works.

**Comment by SkyCraft78** [comment]
The token is not meant to be stored anywhere, options and variables included.
That's why I disabled the expression parsing in the token entry, just put your plain token string and that's all.
