### ISSUE TITLE
[BUG] Unable to loop channels of a guild

### ISSUE THREAD

**Issue by RayAaar** [DiSkyOrg/DiSky#45]
Currently, in disky, it is not possible to loop text channels/channels in general.
(https://user-images.githubusercontent.com/96366079/169241143-b817f909-aee5-4bdc-b98b-30c9c33e3d26.png)
 Any iteration/change of the above syntax does not work either. 
 Please fix this, JDA doesn't even seem to fix this for me.

**Comment by SkyCraft78** [comment]
**Channels** are abstract. They are simply an identifier to represent every sub-channel possible.
You can however loop text, voice, or other channels of the guild.

**Comment by RayAaar** [comment]
> **Channels** are abstract. They are simply an identifier to represent every sub-channel possible.
> You can however loop text, voice, or other channels of the guild.

But loop text channels / loop text-channels of event-guild doesn't work either.

**Comment by SkyCraft78** [comment]
added

**Comment by RayAaar** [comment]
wait will this come in the new disky update? Or is it already added to the existing disky jar.
