### ISSUE TITLE
Channels don't get detected after a crash

### ISSUE THREAD

**Issue by RayAaar** [DiSkyOrg/DiSky#50]
Using the channel id to get a channel works fine, however after you experience a server crash (can be due to load from disky) it is impossible to detect the channel until you make a new channel and a new id to detect.
Here's the error I get after a crash
![image](https://user-images.githubusercontent.com/96366079/172996195-3a2d27f9-cc55-4904-9ce2-2eb2ae600293.jpeg)
I have also made the sure that the id stays the same. I have even trying storing the channel in a variable, however even then doesn't work when you try to name it (after a crash).
Hope this gets fixed soon!

**Comment by SkyCraft78** [comment]
Can you send any code that you think can cause this error?

**Comment by RayAaar** [comment]
set {_vc} to voice channel with id "%{stats::%discord id of loop-guild%::%{server::%discord id of loop-guild%}%::players}%"
set channel name of {_vc} to "Players: %{_response::server::playerCount}%/%{_response::server::maxPlayers}%"

This is the part of my code which is causing the errors. It cannot detect the id after a crash, even though when I broadcast it it is a valid id.
Really confused me

**Comment by wallace4BR** [comment]
> set {_vc} to voice channel with id "%{stats::%discord id of loop-guild%::%{server::%discord id of loop-guild%}%::players}%" set channel name of {_vc} to "Players: %{_response::server::playerCount}%/%{_response::server::maxPlayers}%"
> 
> This is the part of my code which is causing the errors. It cannot detect the id after a crash, even though when I broadcast it it is a valid id. Really confused me

maybe specify the bot in expressions?
is the bot online and able to do another tasks since you said the server had crashed

**Comment by RayAaar** [comment]
> > set {_vc} to voice channel with id "%{stats::%discord id of loop-guild%::%{server::%discord id of loop-guild%}%::players}%" set channel name of {_vc} to "Players: %{_response::server::playerCount}%/%{_response::server::maxPlayers}%"
> 
> > 
> 
> > This is the part of my code which is causing the errors. It cannot detect the id after a crash, even though when I broadcast it it is a valid id. Really confused me
> 
> 
> 
> maybe specify the bot in expressions?
> 
> is the bot online and able to do another tasks since you said the server had crashed

Yes the bot is online. When I delete the channel via the bot, the channels don't delete either and gives another one of those errors. However other commands do continue to work.

**Comment by SkyCraft78** [comment]
When a crash is happening, Skript unload every trigger, the defining scope too. 
That mean the bot is not online anymore, or at least don't have an opened connection to Discord.
Therefore you won't be able to do anything with the bot once the server crashed, such as getting entities as you're doing.

**Comment by RayAaar** [comment]
> When a crash is happening, Skript unload every trigger, the defining scope too.
> That mean the bot is not online anymore, or at least don't have an opened connection to Discord.
> Therefore you won't be able to do anything with the bot once the server crashed, such as getting entities as you're doing.

Just wanted to mention that I am still getting this bug while the bot is ONLINE, and has been online for a while.
I don't know why this bug is constantly happening, because all values seem to be fine.
If you have any other suggestions, please let me know.
