### ISSUE TITLE
[ENHANCEMENT] Other Application Features

### ISSUE THREAD

**Issue by IllagerCaptain** [DiSkyOrg/DiSky#53]
I think it would be cool and useful to have the ability to control other scopes via DiSky, such as `applications.commands.permissions.update`, `identify`, `guilds.join`, etc. in the bot. It could be useful in a lot of ways. For example, `identify` or `guilds` could be a good for alt detector bots.

See https://discord.com/developers/docs/topics/oauth2#client-credentials-grant

**Comment by SkyCraft78** [comment]
This is OAuth2, and will not be added to DiSky directly.
Mabe a module will be made for tht. Small remember, oauth has not a lot to dow ith actual discord bots. It's just an authorization system provided by Discord.
