### ISSUE TITLE
Default Member Permissions

### ISSUE THREAD

**Issue by IllagerCaptain** [DiSkyOrg/DiSky#54]
[Default member permissions](https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-structure#:~:text=default_member_permissions) option for slash commands are currently missing from the add-on.

**Comment by SkyCraft78** [comment]
After searching some minutes this night over JDA's sources, it seems it doesn't support that feature yet. I'll take a deeper looks to the issues and the PRs tomorrow, and if one is available I'll try to add supports for it in 4.1.0.

**Comment by IllagerCaptain** [comment]
> After searching some minutes this night over JDA's sources, it seems it doesn't support that feature yet. I'll take a deeper looks to the issues and the PRs tomorrow, and if one is available I'll try to add supports for it in 4.1.0.

https://github.com/DV8FromTheWorld/JDA/pull/2113

**Comment by SkyCraft78** [comment]
This will be added in one or two versions of DiSky.
I'm waiting for the PR to be merged or the two others.
*I cannot use two different commits (~= pull request) at the same time.*

**Comment by SkyCraft78** [comment]
Correction, DiSky will provide another version containing this.
You can take a look at the new branch I created, modifications related to slass commands permissions will be there.

**Comment by IllagerCaptain** [comment]
> This will be added in one or two versions of DiSky. I'm waiting for the PR to be merged or the two others. _I cannot use two different commits (~= pull request) at the same time._

This was merged, see https://github.com/DV8FromTheWorld/JDA/commit/4fc8c352b5cb078291a8f7be356a694ace178026.

**Comment by SkyCraft78** [comment]
I saw that, it's available on the commits hash i'm currently using.
Won't eb done soon through, check the latest annoucment for more information.

**Comment by SkyCraft78** [comment]
Thanks you!

**Comment by SkyCraft78** [comment]
Added 👍
