### ISSUE TITLE
How can I send last embed to a certain channel

### ISSUE THREAD

**Issue by muhyomuhyo** [DiSkyOrg/DiSky#58]
My code worked on MC1.18.2 Skript 2.5 and Disky 3.6.0-ARK  but after version up to MC 1.19 Skript 2.6 and Disky 4.0.1 ,It does not worked.
how can I amend codes?

[Code]
Before: <WORKED WELL>

```
make new discord bot:
	enable all default intent
	login to "---my token---" with name "---bot Name---"

command /sample command:
	trigger:
		make embed:
			set title of the embed to "....."
			set description of the embed to "...."
			send last embed to channel with id "---text chat channel ID---" with bot "---bot Name---"
```

After: --->CODE ERROR

```
define new bot named "---bot Name---":
	token: {@token}
	intents: default intents
	policy: all
	auto reconnect: true
	compression: none
	
command /sample command:
	trigger:
		make embed:
			set title of the embed to "....."
			set description of the embed to "...."
			send last embed to channel with id "---text chat channel ID---" with bot "---bot Name---"
```

[result]
--->>Can't understand this condition/effect:  send last embed to channel with id "---text chat channel ID---" with bot "---bot Name---"

**Comment by SkyCraft78** [comment]
Can you try to re-format correctly your message, please?

**Comment by muhyomuhyo** [comment]
thx rapid reply! I re-formatted it.

**Comment by SkyCraft78** [comment]
The `send` effect changed, now it became a `post` effect:
https://skripthub.net/docs/?id=7327

**Comment by muhyomuhyo** [comment]
The issue was resolved!
Thank you!
