### ISSUE TITLE
`if player is online` condition stops working when DiSky is installed.

### ISSUE THREAD

**Issue by CheeseTroll** [DiSkyOrg/DiSky#61]
Hello I need some help

When I have DiSky version 4.1.0 installed the `if player is online` condition stops working. I am on skript version 2.6.1 with paper 1.18.2 and DiSky 4.1.0.

I know it's DiSky causing the problem for sure because 1. the issue only started happening when I installed DiSky and 2. it completely fixes itself when DiSky is uninstalled. There are also no errors in console for some reason

**Comment by SkyCraft78** [comment]
Unable to reproduce:
```
on join:
    while player is online:
        send "hey my friend!" to player
        wait a second
```
DiSky had this problem a long time ago but currently, in v4.1.0, there's no syntax with `online` only in it.

**Comment by CheeseTroll** [comment]
Hello

```command /testplayerisonline:
	permission: Admin
	trigger:
		set {_p} to sender
		if {_p} is online:
			broadcast "Why yes I am online!"
		set {_p} to event-player
		if {_p} is online:
			broadcast "Wanna play some murder mystery?"
		set {_p} to player
		if {_p} is online:
			broadcast "Sure!"```
			
When I have DiSky installed with the same version I listed in my original post I still get the same problem 
I also am op so it is not because I dont have permissions
There is still no error in console

**Comment by CheeseTroll** [comment]
@SkyCraft78 sorry for the ping please forgive me 🙏 but are there any updates on this? in the example script I listed you can see  if you store the player in a local variable and try to use that to check if they're online it doesn't work :[. I tested with the latest version of DiSky 4.1.1 and I still get the same problem but the problem disappears when I uninstall DiSky. The problem only happens if you try to check if a player is online through the local variable, you can do ```if sender is online``` and it'll work.

**Comment by wallace4BR** [comment]
Reopening this issue as I may have a fix for it
Please check #63

**Comment by SkyCraft78** [comment]
The issues is finally found. The onlinestatus enum is used instead of the actual Skript expression. 
However, I'm still searching for no breaking - changes fix, cause the entire enum have to be changed.

**Comment by SkyCraft78** [comment]
Check #68, open **a new issue** if it stills occur please!
