### ISSUE TITLE
Unable to properly get author of a deleted message

### ISSUE THREAD

**Issue by IllagerCaptain** [DiSkyOrg/DiSky#65]
> Then you're using the wrong syntax. Check for `author of` expression.

author of expression requires a message but there is no message in message delete event?

_Originally posted by @UsainSrht in https://github.com/DiSkyOrg/DiSky/issues/42#issuecomment-1130268160_

**Comment by SkyCraft78** [comment]
Hey 👋 
Yeah indeed you've right, getting the author requires the actual message.
There's no way to *efficiently* make it works, unfortunately (I could cache the user or just the ID, but it would not be optimized to do that for every message).

> Note: Discord only give us the message's ID when any is deleted

**Comment by SkyCraft78** [comment]
`event-string`

**Comment by IllagerCaptain** [comment]
> `event-string`

I thought that returned the cached message not the message ID?
