### ISSUE TITLE
I can't load my bot

### ISSUE THREAD

**Issue by Lubinrns** [DiSkyOrg/DiSky#72]
I use the last version of disky, on paper 1.19.1 with last version of skript and my can't don't work
![unknown](https://user-images.githubusercontent.com/73492297/182481285-298beec5-2a19-4091-ade7-16e85a18d4ec.png)

code:
```js
define new bot named "xx": 

    token: "xx"

    intents: default intents

    policy: all
    auto reconnect: true
    compression: none
    
    on ready:
        set presence of bot named "xx" to streaming "xx" with url "https://twitch.tv/xx"
```

**Comment by Lubinrns** [comment]
i think 1.19.1 is not supported ?

**Comment by SkyCraft78** [comment]
There's an error right above the one you sent here (the one in yellow)

**Comment by Lubinrns** [comment]
Yes mb my token was invalid, i don't know why but now its fix, ty
