### ISSUE TITLE
Missing message exception in message receive event

### ISSUE THREAD

**Issue by Lubinrns** [DiSkyOrg/DiSky#73]
![Screenshot 2022-08-05 132114](https://user-images.githubusercontent.com/73492297/183067332-b18de069-c364-42cb-9bef-65a332c087b2.png)

Je pense que le problème vient de cette partie de mon code : ![Screenshot 2022-08-05 132546](https://user-images.githubusercontent.com/73492297/183067983-87ef7e32-9a79-44e6-9a99-e80265a72ff9.png)

Car, si j'enlève cette partie du code et que j'utilise uniquement l'autre partir (c'est une commande discord) tout fonctionne

**Comment by SkyCraft78** [comment]
L'effet de purge n'est utile que quand tu supprime plusieurs messages en même temps.
Utilise l'effet destroy à la place, et dis moi si l'erreur est toujours présente.
Le plus probable serait que quelqu'un ai supprimé le message entre temps, ducoup il n'existe plus et impossible de l supprimer à nouveau.

**Comment by Lubinrns** [comment]
D'accord je vois, j'ai donc changé le "purge" par "destroy" et j'ai toujours la même erreur.
J'ai même copié le code vers un autre fichier, supprimer l'ancien code redémarrer le serveur mais toujours la même erreur :/

**Comment by SkyCraft78** [comment]
Tu pourrais débug la variable qui contient ton message à chaque ligne? Discord ne semble pas reconnaitre le message en question donc peut être que tu le modifie entre temps.

**Comment by Lubinrns** [comment]
J'ai debug ma variable qui contient ma suggestion, j'ai supprimé mon fichier variable de skript (je n'avais rien d'important), j'ai retiré le skript, je l'ai remis, j'ai restart le serveur.
Toujours rien, j'ai toujours la même erreur :c

**Comment by wallace4BR** [comment]
if "%event-message%" starts with ".sugg" or ".suggestion"

**Comment by Lubinrns** [comment]
No, but thanks to you, I thought of removing the lower part of my code and it works

**Comment by Lubinrns** [comment]
so, it's solved, my code was just wrong my bad
fr : donc, c'est résolu, mon code était juste faux mb
