### ISSUE TITLE
Suggestion for implementations

### ISSUE THREAD

**Issue by JJKing42** [DiSkyOrg/DiSky#74]
I realize this may be a bit far fetched.. But it would be really cool :b

If DiSky had some basic features imported from youtube and twitch API's.
I like the idea of using DiSky as a one-stop-shop for my discord bot needs. 
So if i was able to link a member who happens to be a content creator, to their respective platforms. ( or just ''listen'' on specific channels)  And then have DiSky post notifications about streams and new uploads.

Currently using IFTTT with webhooks, to avoid adding more bots. But the webhooks keep failing at random.

**Comment by SkyCraft78** [comment]
This could be done through a module, but DiSky won't add that by itself.
