### ISSUE TITLE
Thread Archive/Lock Effect/Expression

### ISSUE THREAD

**Issue by DampfWaffel** [DiSkyOrg/DiSky#80]
Hello,

is there a Thread Archive/Lock Effect/Expression? Or will this be added in the next update?

https://ci.dv8tion.net/job/JDA5/javadoc/net/dv8tion/jda/api/managers/channel/concrete/ThreadChannelManager.html#setArchived(boolean)
https://ci.dv8tion.net/job/JDA5/javadoc/net/dv8tion/jda/api/managers/channel/concrete/ThreadChannelManager.html#setLocked(boolean)

https://ci.dv8tion.net/job/JDA5/javadoc/net/dv8tion/jda/api/entities/ThreadChannel.html#isArchived()
https://ci.dv8tion.net/job/JDA5/javadoc/net/dv8tion/jda/api/entities/ThreadChannel.html#isLocked()

```
on message receive:
    event-member is not discord bot
    set {_x} to event-threadchannel
    "%event-message%" is "check":
        broadcast "C) %{_x}% - %{_x}.isArchived()% // %{_x}.isLocked()%"
    "%event-message%" is "close":
        broadcast "1) %{_x}% - %{_x}.isArchived()% // %{_x}.isLocked()%"
        {_x}.setArchived(true)
        {_x}.setLocked(true)
        broadcast "2) %{_x}% - %{_x}.isArchived()% // %{_x}.isLocked()%"
```

skript wont lock/archive the thread. discord commands do not work in threads / are ignored.
the debug says, Locked and Archived is true but nothing changend in discord itself.
consolse does not show any errors. just the debug

Thanks

**Comment by SkyCraft78** [comment]
Added 👍
