### ISSUE TITLE
Types conflict with Skript

### ISSUE THREAD

**Issue by Lotzyprod** [DiSkyOrg/DiSky#84]
When we compare string with a text, something like:
```
set {_text} to "someWords"
if {_text} is text:
  broadcast "Yes"
```
Its compare variable with types.channeltype, not with text from Skript.

https://github.com/DiSkyOrg/DiSky/blob/4b8588d3eb3679dece0ccabcf3a3b3e219430f1b/src/main/java/info/itsthesky/disky/elements/Types.java#L109

**Comment by SkyCraft78** [comment]
Gonna be changed soon to something else. Thanks for the reports!
