### ISSUE TITLE
Je ne peux pas réagir à un message

### ISSUE THREAD

**Issue by Lubinrns** [DiSkyOrg/DiSky#85]
Bonjour, j'ai une commande de suggestion qui doit réagir à ma suggestion mais j'ai une grosse erreur en question !

Mon erreur :
![image](https://user-images.githubusercontent.com/73492297/188198436-34a1241d-b1e0-4946-a179-6230d8d9b40b.png)

Mon code : 

`discord command suggestion [<text>]:
    aliases: sugg, suggest
    prefixes: .
    executable in: guild
    trigger:
        if arg-1 is set:
            set {_mh} to event-message
            delete {_mh}
            set {_sugg} to arg-1
            set {_auth} to nickname of event-member
            set {_avat} to avatar of event-member
            make new embed:
                set title of embed to ":bulb: **| Suggestion**"
                set description of embed to "%{_sugg}%"
                set author of the embed to "Suggéré par %{_auth}%"
                set author icon of embed to "%{_avat}%"
                set footer of embed to "S*** - By Lubin_rns"#"0001"
                set footer icon of embed to "***"
            post last embed to channel with id "922166243224608898" and store it in {_suggestion}
            react to {_suggestion} with emote "x"
            create new thread named "AVIS | Suggéré par %{_auth}%" in channel with id "922166243224608898" using message {_suggestion} and store it in {_avis}
            post ":warning: Vous avez la possibilité de donner votre avis. %nl%Merci de rester **courtois**." to channel {_avis}
        else:
            make new embed:
                set title of embed to ":bulb: **| Suggestion**"
                set description of embed to ":x: Erreur, merci de proposer une suggestion (supérieur à 5 caractères) !"
                set footer of embed to "** - By Lubin_rns"#"0001"
                set footer icon of embed to "***"`

**Comment by Lubinrns** [comment]
Je re upload mon code : 

```
discord command suggestion [<text>]:
    aliases: sugg, suggest
    prefixes: .
    executable in: guild
    trigger:
        if arg-1 is set:
            set {_mh} to event-message
            delete {_mh}
            set {_sugg} to arg-1
            set {_auth} to nickname of event-member
            set {_avat} to avatar of event-member
            make new embed:
                set title of embed to ":bulb: **| Suggestion**"
                set description of embed to "%{_sugg}%"
                set author of the embed to "Suggéré par %{_auth}%"
                set author icon of embed to "%{_avat}%"
                set footer of embed to "S*** - By Lubin_rns"#"0001"
                set footer icon of embed to "***"
            post last embed to channel with id "922166243224608898" and store it in {_suggestion}
            react to {_suggestion} with emote "x"
            create new thread named "AVIS | Suggéré par %{_auth}%" in channel with id "922166243224608898" using message {_suggestion} and store it in {_avis}
            post ":warning: Vous avez la possibilité de donner votre avis. %nl%Merci de rester **courtois**." to channel {_avis}
        else:
            make new embed:
                set title of embed to ":bulb: **| Suggestion**"
                set description of embed to ":x: Erreur, merci de proposer une suggestion (supérieur à 5 caractères) !"
                set footer of embed to "** - By Lubin_rns"#"0001"
                set footer icon of embed to "***"
```

**Comment by Noqh-Dev** [comment]
Il faut que tu mettes entre 2 points l'émoji, exemple :x:

**Comment by SkyCraft78** [comment]
Le nom ou l'unicode de l'emoji est normalement possible, donc dans ton cas ça devrait marcher.
Quelle est la version de DiSky que tu utilise?

**Comment by Lubinrns** [comment]
J'utilise v4.3.0

**Comment by Lubinrns** [comment]
Le problème ne provient donc pas de mon code ?

**Comment by SkyCraft78** [comment]
Le système d'émoji est assez merdique (par Discord je veux dire), et c'est assez complexe pour moi de savoir quel type d'émoji (si c'est unicode = emojis de base de Discord, ou custom = emojis venant de serveurs) on essaye de récupérer. 
J'ai encore changer la méthode de récupération dans le code de DiSky, en espérant que ça fixera le soucis.
Tu peux jeter un oeil aux actions si tu veux déjà la tester d'ailleurs!

**Comment by SkyCraft78** [comment]
Rouvre cette issue si l'erreur est toujours présente.

**Comment by Lubinrns** [comment]
Oui je comprends le système d'émoji de discord.
J'ai télécharger la version "Changed how to parse emojis", et j'ai toujours le erreur, toujours avec le même code.
J'ai essayé des variantes `react with emote`, `react with reaction` mais ça ne fonctionne toujours pas.

**Comment by SkyCraft78** [comment]
Fixé, le soucis venait de la react section qui n'utilisait que l'emoji custom (les emojis unicode ne marchaient donc pas)

**Comment by Lubinrns** [comment]
Merci beaucoup après test, ça fonctionne !
