### ISSUE TITLE
function read error on startup and script load

### ISSUE THREAD

**Issue by Unity-RE** [DiSkyOrg/DiSky#86]
I'm guessing there's a function event in DiSky, since upon adding DiSky 4.4.0+ (haven't tested on previous versions)
it causes all functions in a server to not be called, and instead ignored, spamming the console with errors.

example error:
"[08:21:12 INFO]: [Skript] Couldn't resolve call for 'arcane'. Be careful when using functions in 'script load' events!"

I haven't put this function in a "on script load:" or "on load:" event, rather used it in a loop to animate ranks for my server.

**Comment by SkyCraft78** [comment]
Codes? Any related codes to DiSky?

**Comment by Unity-RE** [comment]
have since been fixed in DiSky V4.4.2, As "If {_txt} is text" tie's greatly into the conflixt, "Set {_txt} to text" and, and "If {_txt} is text" is used in the mentioned skript above.
