### ISSUE TITLE
Suggestion for destroy effect

### ISSUE THREAD

**Issue by Pirania3680** [DiSkyOrg/DiSky#87]
Disky's destroy effect collides with the same effect from the skent addon. A lot of people says it works for them, but it definitely doesn't work for me. When I uninstalled Skent, messages on discord are removed, but when I restore Skent, discord messages are intact.

Suggestion: Add something that distinguishes this effect from the skent effect:
disky destroy %guild/message/role/channel/emote%
destroy discord entity %guild/message/role/channel/emote%
discord destroy %guild/message/role/channel/emote%

I asked for help on Discord but only one answer: It works for me...

[Skript 2.6, Disky 4.4.2, Skent 3.1.0]

**Comment by SkyCraft78** [comment]
As said a lot of times before, I am willing to fix conflicts if, and only if, they come from Skript directly.
I'm sorry, but I cannot change a whole syntax like this one just for one small addon such as Skent.
