### ISSUE TITLE
Bug Eco lib and plugins

### ISSUE THREAD

**Issue by Keopsfenks** [DiSkyOrg/DiSky#88]
https://github.com/Auxilor/eco/issues/194

**Comment by SkyCraft78** [comment]
I don't have a single idea of why it's happening, ask the eco's developers.
DiSky is made in Java, not Kotlin.

**Comment by Keopsfenks** [comment]
Thank you for understanding.

**Comment by SkyCraft78** [comment]
Is there any news on this issue?
