### ISSUE TITLE
Posting messages don't work

### ISSUE THREAD

**Issue by R3241** [DiSkyOrg/DiSky#92]
I am trying to send a message in a channel provided in a channel using the post effect, no errors appear but the message won't post. The reply effect with a discord command works fine. My code:
```
command /linkchannel [<text>] [<text>]:
	permission: op
	trigger:
		if arg-1 is "default":
			message "code for default channel"
		else if arg-1 is "remoteconsole":
			if arg-2 is not set:
				message "To connect to a channel type /linkchannel remoteconsole <channel id>"
				message "&To disconnect the console type &f/skriptcord-link -"
			else:
				if arg 2 parsed as number is a number:
					if arg 2 parsed as textchannel is a textchannel:
						post "a" to text channel with id arg-2
					else:
						message "&cCouldn't find the text channel."
				else:
					message "&cType the channel ID, not the name."
		else if arg-1 is "log":
			message "code for logging"
```
I tried creating separate commands for posting a message into a channel, one with an argument, and one without (I provided the channel id), but to no avail. In every command channel id was provided correctly.
I have no idea what I might be doing wrong, so please correct me if necessary.

**Comment by Devc2** [comment]
Do `reply with` instead of message

**Comment by CerialPvP** [comment]
It is not a bug, you just need to use channel with id instead of text channel with id

**Comment by CerialPvP** [comment]
> Do `reply with` instead of message

No the message is messaging ingame not in discord

**Comment by R3241** [comment]
> It is not a bug, you just need to use channel with id instead of text channel with id

omg thank you !!!
