### ISSUE TITLE
Emote/Reaction "100" is not useable.

### ISSUE THREAD

**Issue by Brickwrath** [DiSkyOrg/DiSky#93]
The 💯 reaction cannot seem to be called by DiSky; using something like:
`add new secondary button with id "d100" named "D100" with reaction "100" to components of the row builder`
causes errors in use, such as:
`"100" is not a types.emote` when calling it an emote, and `You must specify a guild when retrieving an emote by its ID!` when calling it a reaction.
Perhaps giving it an alias such as `hundred` or `one_hundred` so it can be called?

**Comment by CerialPvP** [comment]
you can try using the unicode, but that is really an interesting bug.

**Comment by SkyCraft78** [comment]
Try to find it in the emojis JSON file, where DiSky takes them. I'll definitely go take a look when I'll got the time though.

**Comment by SkyCraft78** [comment]
According to the file that DiSky uses for emojis, it's been here:
![image](https://user-images.githubusercontent.com/50667548/201178290-18f121e6-03d3-4b7a-9bde-567818ee4488.png)
Lines: 10 661 to 10 668
The only shortcode associated with it is `100`, can you try again or try the Unicode?

**Comment by SkyCraft78** [comment]
Okay, I think it comes from the expression that does not parse it accurately; it may think it's an ID you're providing and not an actual emoji. I changed that, therefore now it's up to 5 numbers to be considered an ID.
