### ISSUE TITLE
Conflict with SkBee 2.5.1 text components

### ISSUE THREAD

**Issue by not-3than** [DiSkyOrg/DiSky#94]
Ok, this has taken me hours today to figure it out, but I have finally figured it out.

At first, I noticed SkBee text components with hover events were not displaying properly, and it took me all of 11 hours figure out that DiSky was the culprit. Upon uninstalling DiSky v4.6.0, the text component hover events worked perfectly, but reinstalling caused them to stop working again. By installing different DiSky versions, I've deciphered that v4.3.0 is the last DiSky version where it does NOT affect SkBee's text components, and v4.4.0 is where it starts to affect it.

### Versions so you can replicate this process
Skript version: v2.6.3
SkBee version: v2.5.1
DiSky version: v4.6.0
Server: PaperMC 1.18.2 (or 1.19.2, both have the bug)

### Steps to replicate this process
1. Install DiSky v4.4.0 (or later), SkBee v2.5.1, and Skript v2.6.3.
2. Run this code:
```
command /textcomponent:
	trigger:
		set {_t} to text component from "Hello, SkBee is a very good plugin."
		set hover event of {_t} to new hover event showing tool
		send component {_t}
```
3. It will send a blank line instead of "Hello, SkBee is a very good plugin." with the hover event.

This is a problem that started happening when DiSky updated to v4.4.0, I suggest this be addressed ASAP, so I can use the latest version of DiSky again. For the time being, I will be using DiSky v4.3.0.

**Comment by Devc2** [comment]
So disky 4.4.3 dosent work either?

**Comment by SkyCraft78** [comment]
This repository is only for DiSky v4+
No supports is given for older version.

**Comment by not-3than** [comment]
Sorry, I meant to put v4.4.0 and not v2.4.0. This happens on the latest versions.

**Comment by not-3than** [comment]
Can this be re-opened?

**Comment by SkyCraft78** [comment]
Ah yes sure, is this still happening on 4.6.0?

**Comment by SkyCraft78** [comment]
The issue with DiSky has been found, and will be fixed this evening!
Thanks for the reports.

**Comment by SkyCraft78** [comment]
Issue fixed, thanks again for the report!

**Comment by not-3than** [comment]
@SkyCraft78 How can I download the version where it is fixed?
