### ISSUE TITLE
Add/Remove Member from Thread

### ISSUE THREAD

**Issue by DampfWaffel** [DiSkyOrg/DiSky#95]
Syntax to add/remove User (with or without) to a Thread.

https://ci.dv8tion.net/job/JDA5/javadoc/net/dv8tion/jda/api/entities/ThreadChannel.html#addThreadMember(net.dv8tion.jda.api.entities.Member)

Threads > Forums :)

**Comment by SkyCraft78** [comment]
Indeed, this is not yet included in DiSky, but will be soon c:
Thanks for the idea!

**Comment by SkyCraft78** [comment]
Has been added, thanks for the idea!
