### ISSUE TITLE
xx

### ISSUE THREAD

**Issue by vCren** [DiSkyOrg/DiSky#97]
Make free transcript add-ons etc, or a one-time access fee. A monthly subscription does not make total sense, it scares off new disky users. Paying $ 5 a month for full access to updates doesn't make total sense. Better would be a one-time access for e.g. $ 2/3

**Comment by CerialPvP** [comment]
tbh i think all the modules should be free, no one will buy jar files just to get extra features considering there are not many people using disky

**Comment by SkyCraft78** [comment]
This is the only way for me to have a passive income on DiSky, so choose between these two:
* Paying 5$ per month for modules & Super plugins
* Paying DiSky one-time for ~10/20$
Much people are gonna chose modules over DiSky itself, so I'll keep it that way :)
