### ISSUE TITLE
locked and archived state of thread?

### ISSUE THREAD

**Issue by DampfWaffel** [DiSkyOrg/DiSky#98]
Hi, is there any way to detect a locked or archived thread?
i only found the effect to lock / archiv threads but not expression

The bot responds with buttons in threads and if it is locked, it should ignore the clicks.

And how do I use `embeds of event-message`? it returns only an empty character

**Comment by SkyCraft78** [comment]
* `is public/archived/locked` conditions added!
* `embeds of event-message` returns an array of EmbedBuilder
