### ISSUE TITLE
weird attachment download

### ISSUE THREAD

**Issue by DampfWaffel** [DiSkyOrg/DiSky#99]
![image](https://user-images.githubusercontent.com/19693397/202875350-23a47f78-d1d5-4d76-97f9-3efba0b854f9.png)

The syntax says that we have to enter a folder path, but this is wrong.
We specify both the location and the file/file type.

```
on message Receive:
	set {_x::*} to attachments of event-message
	download {_x::1} in folder "../plugins.png"
	broadcast "done?"
```

if i just enter a folder:
![image](https://user-images.githubusercontent.com/19693397/202875375-a7b51bcf-f8f0-435a-a797-0c5387d5dd61.png)

**Comment by CerialPvP** [comment]
You need to specify the path from the server's root folder
For example `./plugins/yourfolder/example.txt`

**Comment by DampfWaffel** [comment]
as I understand it, I should only specify the order path and then it downloads the file as it was originally uploaded on discord(including name + type).

but currently you have also to specify the name + type.

**Comment by Devc2** [comment]
Wait disky 4.7.0?

**Comment by SkyCraft78** [comment]
Fixed this, allowing both directories (the file's name will be the attachment name) and files.
